---
# handlers file for jenkins
- name: install_jenkins
  apt:
    name: jenkins
    state: present


- name: Restart and enable and reload daemon service for jenkins
  ansible.builtin.systemd_service:
    state: started
    daemon_reload: true
    name: jenkins
    enabled: true  
